<?php
	require_once('functions.php');
	require_once('read.php');
	require_once('sessions.php');
	require_once('login.php');
	require_once('user.php');
	require_once('rates.php');
	require_once('sched.php');
	require_once('news.php');
	require_once('thumbnail.php');
?>